services:
  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress_site
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-projeto-wordpress.ck2uq470e02b.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: $senhadobanco
      WORDPRESS_DB_NAME: $nomedobancodedados
    volumes:
      - /mnt/efs:/var/www/html
